{% set name = "geoarray" %}
{% set version = "0.8.37" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 977082c06d3c2016b05c636349e90b442eedf32de566727eb9fbe2c6513cb5ec

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - basemap
    - dill
    - folium
    - gdal >=2.1.0
    - geojson
    - matplotlib-base
    - mpld3
    - numpy
    - pandas
    - py-tools-ds >=0.14.35
    - python
    - scikit-image
    - shapely
    - six

test:
  imports:
    - geoarray
    - geoarray.baseclasses
    - geoarray.masks
    - geoarray.metadata
    - geoarray.subsetting
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://pypi.org/project/geoarray/
  summary: Fast Python interface for geodata - either on disk or in memory.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
